version: "3.9"

services:
  mongo:
    image: "mongo:6.0.8"
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
  neo4j:
    image: "neo4j:5.9.0"
    ports:
      - 7687:7687
      - 7474:7474
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - USERNAMES=johndoe,janesmith
      - NAMES=John Doe,Jane Smith
      - PASSWORDS=password1,password2
      - SECRET_KEY=my_secret_key
